spring.application.name=SecurityProject2
spring.datasource.url=jdbc:postgresql://localhost:5432/SecurityProject
spring.datasource.username=postgres
spring.datasource.password=#Richard2018
spring.datasource.driver-class-name=org.postgresql.Driver

# Cria/atualiza automaticamente as tabelas no banco de dados
spring.jpa.hibernate.ddl-auto=update

# Exibe as consultas SQL no console para facilitar a depuração
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true